[project]
name = "liveengine"
version = "0.1.0"
description = "Engine of my little game Live"
readme = "README.md"
requires-python = ">=3.15"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = ["--import-mode=importlib"]

[tool.ruff]
line-length = 80
